// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function GetBookPath():Promise<string>;

export function GetFirstTenRecentBooks():Promise<Array<models.Book>>;
