// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBookFromPath(arg1) {
  return window['go']['main']['App']['GetBookFromPath'](arg1);
}

export function GetBookPath() {
  return window['go']['main']['App']['GetBookPath']();
}

export function GetFirstTenRecentBooks() {
  return window['go']['main']['App']['GetFirstTenRecentBooks']();
}

export function OpenFolderAndCreateALibrary() {
  return window['go']['main']['App']['OpenFolderAndCreateALibrary']();
}

export function TraverseThroughDirectoryAndAddToDb(arg1, arg2) {
  return window['go']['main']['App']['TraverseThroughDirectoryAndAddToDb'](arg1, arg2);
}
